server:
  servlet:
    context-path: /api

app:
  mock-data:
    enabled: false

spring:
  data:
    redis:
      host: localhost
      port: 6379
    cache:
      type: redis
    rest:
      base-path: /dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bankschema?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ComicCrane110%

  jpa:
    properties:
      hibernate:
        id:
          new_generator_mappings: false
ext-api:
  mock:
    use-mock-data: false
    mock-data-url: "https://69062183ee3d0d14c134ec0c.mockapi.io/api/v1/getRates"
  exchange:
    uri: "https://api.exchangeratesapi.io/v1/latest?access_key="
    access-token: "33706f6031e3d0fefb453f2d9940b449"

logging:
  level:
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG
    org.springframework.cache: DEBUG
